name: echopype
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - cmocean
  - echopype==0.5.4
  - h5netcdf==0.11.0
  - matplotlib
  - numpy
  - pandas
  - pillow
  - python-dateutil
  - xarray
