name: echogram
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - argcomplete
  - cmocean
  - echopype
  - h5netcdf
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - python-dateutil
  - tqdm
  - xarray
