name: echogram
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - argcomplete
  - bottleneck
  - cmocean
  - conda-build
  - echopype>=0.8.1
  - h5netcdf
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - python-dateutil
  - tqdm
  - xarray
