name: echopype
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - cmocean
  - echopype
  - h5netcdf
  - matplotlib
  - numpy
  - pandas
  - pillow
  - python-dateutil
  - xarray
